[alias]
r = "run --target xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "probe-rs run"

[target.'cfg(target_arch = "xtensa")']
rustflags = [
    "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "trace"
